### ISSUE TITLE
Some question about labml

### ISSUE THREAD

**Issue by YYY-12138** [kyrie-23/federated_diffusion#1]
I'd like to know how to deal with"
LABML WARNING: [Errno 2] No such file or directory Failed to connect:https://api.labml.ai/api/v1/trackrun_uuid=dcafea30be3c11edb55ef875a4af118a&labml_version=0.4.161"

**Comment by kyrie-23** [comment]
Did you encouter this issue while sampling? You need to specify an uuid from trained logs in the function main().
Please check the readme and contact me if there's further question.
